# Generated by Django 3.2.9 on 2021-11-03 00:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0003_auto_20211103_0040'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usuario',
            old_name='user',
            new_name='datos',
        ),
    ]
