# Generated by Django 3.2.8 on 2021-11-05 19:13

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('usuarios', '0004_rename_user_usuario_datos'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Usuario',
            new_name='UserProfile',
        ),
    ]
