# Generated by Django 3.2.9 on 2021-11-19 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0006_userprofile_cv'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='verificado',
            field=models.BooleanField(default=False),
        ),
    ]
