# Generated by Django 3.2.9 on 2021-11-19 20:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0007_userprofile_verificado'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='verificado',
        ),
    ]
