# Generated by Django 3.2.8 on 2021-11-16 23:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('usuarios', '0006_userprofile_cv'),
    ]

    operations = [
        migrations.CreateModel(
            name='Publicacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('puesto', models.CharField(max_length=150)),
                ('descripcion', models.TextField()),
                ('area', models.CharField(max_length=100)),
                ('localidad', models.CharField(max_length=50)),
                ('sueldo', models.IntegerField()),
                ('tipo', models.CharField(max_length=50)),
                ('modalidad', models.CharField(max_length=50)),
                ('url', models.CharField(max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios.userprofile')),
                ('postulantes', models.ManyToManyField(related_name='postulantes', to='usuarios.UserProfile')),
            ],
        ),
    ]
