# Generated by Django 3.2.8 on 2021-11-17 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0006_userprofile_cv'),
        ('publicaciones', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publicacion',
            name='postulantes',
            field=models.ManyToManyField(related_name='postulaciones', to='usuarios.UserProfile'),
        ),
    ]
