# Generated by Django 3.0.7 on 2021-11-24 15:15

import CV.models
import django.contrib.postgres.fields
import django.contrib.postgres.fields.hstore
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CV',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, null=True)),
                ('apellido', models.CharField(max_length=50, null=True)),
                ('DNI', models.BigIntegerField(null=True)),
                ('fecha_nacimiento', models.CharField(max_length=15, null=True)),
                ('genero', models.CharField(max_length=15, null=True)),
                ('nacionalidad', models.CharField(max_length=20, null=True)),
                ('localidad', models.CharField(max_length=50, null=True)),
                ('codigo_postal', models.BigIntegerField(null=True)),
                ('direccion', models.CharField(max_length=50, null=True)),
                ('telefono', models.BigIntegerField(null=True)),
                ('email', models.EmailField(max_length=254, null=True)),
                ('disponibilidad_viajar', models.BooleanField(blank=True, null=True)),
                ('disponibilidad_mudarse', models.BooleanField(blank=True, null=True)),
                ('movilidad_propia', models.BooleanField(blank=True, null=True)),
                ('perfil', models.TextField(blank=True, default='', null=True)),
                ('habilidades', models.TextField(blank=True, default='', null=True)),
                ('imagen', models.ImageField(blank=True, default='profile_pics/fotocv.png', null=True, upload_to='profile_pics')),
                ('licencias', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=10), default=CV.models.licencia_default, null=True, size=None)),
                ('idiomas', django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.hstore.HStoreField(), blank=True, default=CV.models.arreglo_vacio, null=True, size=None)),
                ('experiencia', django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.hstore.HStoreField(), blank=True, default=CV.models.arreglo_vacio, null=True, size=None)),
                ('estudios', django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.hstore.HStoreField(), blank=True, default=CV.models.arreglo_vacio, null=True, size=None)),
                ('completo', models.BooleanField(blank=True, default=False, null=True)),
            ],
        ),
    ]
