# Generated by Django 3.2.9 on 2021-11-09 12:59

import django.contrib.postgres.fields
import django.contrib.postgres.fields.hstore
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CV',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('DNI', models.IntegerField()),
                ('fecha_nacimiento', models.CharField(max_length=15)),
                ('genero', models.CharField(max_length=15)),
                ('nacionalidad', models.CharField(max_length=20)),
                ('localidad', models.CharField(max_length=50)),
                ('codigo_postal', models.IntegerField()),
                ('direccion', models.CharField(max_length=50)),
                ('telefono', models.IntegerField()),
                ('email', models.EmailField(max_length=254)),
                ('disponibilidad_viajar', models.BooleanField()),
                ('disponibilidad_mudarse', models.BooleanField()),
                ('movilidad_propia', models.BooleanField()),
                ('perfil', models.TextField()),
                ('habilidades', models.TextField()),
                ('imagen', models.FileField(null=True, upload_to='')),
                ('licencias', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=5), null=True, size=None)),
                ('experiencia', django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.hstore.HStoreField(), size=None)),
                ('estudios', django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.hstore.HStoreField(), size=None)),
                ('completo', models.BooleanField(default=False)),
            ],
        ),
    ]
