# Generated by Django 3.2.9 on 2021-11-09 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CV', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cv',
            name='DNI',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='cv',
            name='codigo_postal',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='cv',
            name='telefono',
            field=models.BigIntegerField(),
        ),
    ]
