# Generated by Django 3.2.9 on 2021-11-09 13:21

import django.contrib.postgres.fields
import django.contrib.postgres.fields.hstore
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CV', '0002_auto_20211109_1311'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cv',
            name='DNI',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='cv',
            name='codigo_postal',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='cv',
            name='completo',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='cv',
            name='direccion',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='cv',
            name='disponibilidad_mudarse',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='cv',
            name='disponibilidad_viajar',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='cv',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='cv',
            name='estudios',
            field=django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.hstore.HStoreField(), blank=True, null=True, size=None),
        ),
        migrations.AlterField(
            model_name='cv',
            name='experiencia',
            field=django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.hstore.HStoreField(), blank=True, null=True, size=None),
        ),
        migrations.AlterField(
            model_name='cv',
            name='fecha_nacimiento',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='cv',
            name='genero',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='cv',
            name='habilidades',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='cv',
            name='imagen',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='cv',
            name='localidad',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='cv',
            name='movilidad_propia',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='cv',
            name='nacionalidad',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='cv',
            name='nombre',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='cv',
            name='perfil',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='cv',
            name='telefono',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
