# Generated by Django 3.2.9 on 2021-11-09 13:22

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CV', '0003_auto_20211109_1321'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cv',
            name='licencias',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=5), default=['N', 'o', ' ', 'P', 'o', 's', 'e', 'e'], null=True, size=None),
        ),
    ]
