# Generated by Django 3.2.9 on 2021-11-09 13:24

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CV', '0004_alter_cv_licencias'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cv',
            name='licencias',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=5), default=[], null=True, size=None),
        ),
    ]
