# Generated by Django 3.2.9 on 2021-11-10 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CV', '0006_alter_cv_licencias'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cv',
            name='DNI',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='cv',
            name='codigo_postal',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='cv',
            name='direccion',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='cv',
            name='email',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='cv',
            name='fecha_nacimiento',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='cv',
            name='genero',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='cv',
            name='localidad',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='cv',
            name='nacionalidad',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='cv',
            name='nombre',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='cv',
            name='telefono',
            field=models.BigIntegerField(null=True),
        ),
    ]
