# Generated by Django 3.2.8 on 2021-11-12 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CV', '0007_auto_20211110_0240'),
    ]

    operations = [
        migrations.AddField(
            model_name='cv',
            name='conocimientos_y_habilidades',
            field=models.TextField(blank=True, null=True),
        ),
    ]
