# Generated by Django 3.2.8 on 2021-11-12 22:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CV', '0008_cv_conocimientos_y_habilidades'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cv',
            name='conocimientos_y_habilidades',
        ),
    ]
