# Generated by Django 3.2.8 on 2021-11-12 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CV', '0009_remove_cv_conocimientos_y_habilidades'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cv',
            name='habilidades',
            field=models.TextField(blank=True, default='', null=True),
        ),
    ]
