# Generated by Django 3.2.8 on 2021-11-13 00:46

import CV.models
import django.contrib.postgres.fields
import django.contrib.postgres.fields.hstore
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CV', '0010_alter_cv_habilidades'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cv',
            name='estudios',
            field=django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.hstore.HStoreField(), blank=True, default=CV.models.arreglo_vacio, null=True, size=None),
        ),
        migrations.AlterField(
            model_name='cv',
            name='experiencia',
            field=django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.hstore.HStoreField(), blank=True, default=CV.models.arreglo_vacio, null=True, size=None),
        ),
    ]
