# Generated by Django 3.2.8 on 2021-11-13 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CV', '0011_auto_20211113_0046'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cv',
            name='perfil',
            field=models.TextField(blank=True, default='', null=True),
        ),
    ]
