# Generated by Django 3.2.8 on 2021-11-14 16:11

import CV.models
import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CV', '0012_alter_cv_perfil'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cv',
            name='licencias',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=10), default=CV.models.licencia_default, null=True, size=None),
        ),
    ]
