# Generated by Django 3.2.8 on 2021-11-14 22:33

import CV.models
import django.contrib.postgres.fields
import django.contrib.postgres.fields.hstore
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CV', '0013_alter_cv_licencias'),
    ]

    operations = [
        migrations.AddField(
            model_name='cv',
            name='idiomas',
            field=django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.hstore.HStoreField(), blank=True, default=CV.models.arreglo_vacio, null=True, size=None),
        ),
    ]
