# Generated by Django 3.2.8 on 2021-11-15 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CV', '0014_cv_idiomas'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cv',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='profile_pics'),
        ),
    ]
