# Generated by Django 3.2.8 on 2021-11-16 00:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CV', '0017_alter_cv_imagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cv',
            name='imagen',
            field=models.ImageField(blank=True, default='profile_pics/fotocv.png', null=True, upload_to='profile_pics'),
        ),
    ]
